[package]
name = "jazz_networks"
version = "0.1.0"
authors = ["Terrence Lam <skyuplam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.5"
